#!/usr/bin/env node

require('./lib/src/ghostly-cli').main()
    .catch((ex) => {
        process.stdout.write('\n' + (ex && ex.stack || ex) + '\n');
        return 64;
    })
    .then((rc) => {
        setTimeout(() => process.exit(rc || 0), 100);
    });
