#!/usr/bin/env node

require('./lib/src/ghostly-cli').main()
    .catch((err) => {
        console.error(String(err), JSON.stringify(err, null, 4));
        return 70;
    })
    .then((rc) => {
        process.exit(rc);
    });
